name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: |
            requirements.txt
      - name: Install system-level dependencies
        run: sudo apt-get update && sudo apt-get install libpoppler-cpp-dev
      - name: Setup venv
        run: |
          uv venv --python 3.12
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install dependencies
        run: uv pip sync requirements.txt
